name = "SchrodingerToolkit"
uuid = "57a3ea83-98de-405a-af08-8160a20b51a6"
authors = ["walexaindre <walexaindre@hotmail.com\n> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
